apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-analyzer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-analyzer
  template:
    metadata:
      labels:
        app: stock-analyzer
    spec:
      containers:
      - name: stock-analyzer
        image: stock-analyzer:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: analyzer-config
              key: redis_host
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: analyzer-secrets
              key: openai_api_key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-analyzer-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: stock-analyzer